export { Navigation } from "./navigation";
export { HeroSection } from "./hero-section";
export { AboutSection } from "./about-section";
export { ProjectsSection } from "./projects-section";
export { ExperienceSection } from "./experience-section";
export { EducationSection } from "./education-section";
export { SkillsSection } from "./skills-section";
export { ContactSection } from "./contact-section";
export { Footer } from "./footer";
